---
services:
  db:
    # yamllint disable-line rule:line-length
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql
      - .data/db_dumps:/db_dumps

  app:
    <<: &COMMON
      build:
        args:
          - PROJECT_NAME
        context: .
        dockerfile: docker/app/Dockerfile
        target: build-python
      environment:
        - DEBUG=${DEBUG:-1}
        - DJANGO_ENV=${DJANGO_ENV:-development}
        - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
        - SECRET_KEY=not-secret
        - TEMPLATE_DEBUG=${TEMPLATE_DEBUG:-1}
      restart: on-failure
      depends_on:
        - db
        - tailwind
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${PORT:-8000}:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/.venv

  tailwind:
    build:
      args:
        - PROJECT_NAME
      context: .
      dockerfile: docker/app/Dockerfile
      target: build-node
    command: npm run tailwind-watch
    tty: true
    stop_grace_period: 0s
    volumes:
      - ./:/app
      - /app/node_modules # node_modules is not shared with the host

volumes:
  client:
  pgdata:
